# Generated by Django 5.1.4 on 2026-09-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedrecord",
            name="availability",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="scrapedrecord",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="scrapedrecord",
            name="price",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="scrapedrecord",
            name="rating",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="scrapedrecord",
            name="content_hash",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="scrapedrecord",
            constraint=models.UniqueConstraint(
                fields=("job", "content_hash"), name="unique_record_per_job"
            ),
        ),
    ]
