# Generated by Django 5.1.4 on 2026-09-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_scrapedrecord_availability_scrapedrecord_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrapedrecord",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="scrapedrecord",
            name="category",
        ),
        migrations.RemoveField(
            model_name="scrapedrecord",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="scrapedrecord",
            name="price",
        ),
        migrations.RemoveField(
            model_name="scrapedrecord",
            name="rating",
        ),
        migrations.AddField(
            model_name="scrapedrecord",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
