# Generated by Django 5.1.4 on 2026-10-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_atlas_platform_upgrade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobrun',
            new_name='core_jobrun_job_id_8635ef_idx',
            old_name='core_jobrun_job_id_4ef7f5_idx',
        ),
        migrations.RenameIndex(
            model_name='scrapedrecord',
            new_name='core_scrape_job_id_91d5b5_idx',
            old_name='core_scrapej_job_id_9d7d4f_idx',
        ),
        migrations.RenameIndex(
            model_name='scrapedrecord',
            new_name='core_scrape_record__ad0f11_idx',
            old_name='core_scraped_record_6d1f4a_idx',
        ),
        migrations.RenameIndex(
            model_name='scrapejob',
            new_name='core_scrape_user_id_639468_idx',
            old_name='core_scrapej_user_id_7f0b34_idx',
        ),
        migrations.RenameIndex(
            model_name='scrapejob',
            new_name='core_scrape_user_id_ec8b8e_idx',
            old_name='core_scrapej_user_id_9d6a4b_idx',
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
